version: '2.1'


services:

  rd-location-ref-data-db:
    build:
      context: database
    image: hmcts/rd-location-ref-data-db
    container_name: rd-location-ref-data-db
    volumes:
      - rd-location-ref-data-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-locrefdata}"
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
    ports:
      - 5458:5432

volumes:
  rd-location-ref-data-db-volume:
